### ISSUE TITLE
DOI for GSW-C

### ISSUE THREAD

**Issue by castelao** [TEOS-10/GSW-C#56]
Does GSW-C have a DOI? I would like to be able to properly cite it. The same DOI could be used to link GSW-Python, GSW-R, and others to it.

Zendo is probably the most convenient way of doing that. I would be happy to help.

**Comment by efiring** [comment]
@castelao That sounds like a good idea.  @ocefpaf, @PaulMBarker, do you have any thoughts on this, or objections?

**Comment by PaulMBarker** [comment]
I am of two minds on this and can be swayed either way.
I can see it makes it easy to reference the code version but it then implies every version of GSW should have its own DOI.
If you do go with it then I must insist that whenever it is used, the original GSW reference is also listed as this details the fundamental ideas of TEOS-10.

**Comment by castelao** [comment]
@efiring  and @PaulMBarker , there are many ways to use DOIs. Since we use GitHub, it is quite convenient to use Zenodo in automatic mode, which would result in a new DOI for each release.

- A DOI per release is useful for reproducibility. Let's imagine a release in which we missed a bug in it. It would be possible to track down publications based on that release.
- If a specific version is not important, one can use an overarching DOI created by Zenodo that always points to the latest version. This one is convenient to converge citations if that is important.
- With a `.zenodo.json` we can configure some of the fields recorded with the DOI, such as references like we would do in the bibliography of a paper. This would be the place to add all those references. If interested in finding some possible fields, such as funding agencies, [check this](https://github.com/castelao/inception).

Here is a practical example with a real DOI [10.5281/zenodo.5348561](https://doi.org/10.5281/zenodo.5348561):
- 10.5281/zenodo.5348561 is the overarching one, always pointing to the latest release;
- 10.5281/zenodo.7192377 is the latest release, specific for 0.0.11
- Note the references in the third box on the right side, which came from the [.zenodo.json](https://github.com/castelao/GSW-rs/blob/main/.zenodo.json). That included the 'TEOS-10 Manual', the 'Getting started with TEOS-10', and more to be included. Like a regular paper, these references are recorded in the DOI database as citing those references.

Just to be clear, we create the `.zenodo.json` once, link Zenodo with the repository, and everything goes automatic for each release.

**Comment by PaulMBarker** [comment]
I agree with the benefit of the points you are making with exception to the last one in your practical example. As I wrote earlier, if you use GSW in any language we expect the end user to include the Getting Started document as an additional reference (because this helps ensure that they use the software in a proper manner oceanographically), not just having it listed as a citation in the DOI as you have done.
 
Furthermore, I have had a good look at your example and see that you have not included the original GSW license but have constructed 2 new licenses.  This is not acceptable, the original license MUST be included with any translated version of GSW. I am not sure it is correct for you to make a license, assigning it to yourself without communicating with the original authors as there is many years of intellectual thought that has gone into both GSW and SIA.  The development of TEOS-10 and its GSW code happened under the watchful eye of SCOR and IAPSO, and it these bodies and their ongoing Joint Committee of Seawater that gives the software its legitimacy.  This must be respected in all versions of the code, including those versions that are in new computer languages.

**Comment by castelao** [comment]
@PaulMBarker, I'm sorry that you see it this way. I have much respect for your work, the rest of the TEOS-10 committee, and fellow open-source contributors to engage in an aggressive discussion with you. I suggest you change the tone so we can have a productive discussion to understand if there were unintentional mistakes and how to address those as well as clarify any misunderstanding.

It sounds to me adequate to include the recommendation on GSW-rs for the users to also cite the Getting started document as well, but it would be incoherent to leave the report MG-56 out of this. I'll add a recommendation to cite both and address this in that repository. Please be welcome to add your comments there. Thanks for pointing that out. It is worth noting that when we write a scientific paper, we must cite the references on which it was based as well as cite the relevant previous works. It would be improper to omit such references. We do cite the references in GSW-rs as we advance the developments over there, so what we did was not wrong. Keep in mind that I initiated this discussion by asking for a way to properly acknowledge GSW-C.

To be able to discuss the matter regarding licenses, could you kindly point to me what you refer to as the original license? Within the different implementations of TEOS-10 (https://github.com/TEOS-10), I see different licenses or no licenses at all.

**Comment by efiring** [comment]
@castelao The license is 
http://www.teos-10.org/pubs/gsw/html/gsw_licence.html
linked from http://www.teos-10.org/software.htm.
I haven't done a diff, but it should match https://github.com/TEOS-10/GSW-C/blob/master/LICENSE.

**Comment by PaulMBarker** [comment]
Over 10 years ago we, Trevor McDougall and myself, opted to ask users to cite Getting started if they use GSW regardless of which version they use. This appears on the TEOS-10 software page, http://www.teos-10.org/software.htm, above the download buttons.

**Comment by castelao** [comment]
@efiring and @PaulMBarker , thanks for pointing to the license. Indeed it is very clear in teos-10.org, but no so clear at GitHub.
